const KEY='gotit.items.v5';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let items=JSON.parse(localStorage.getItem(KEY)||localStorage.getItem('gotit.items.v4')||'[]');
let selectedSpace='Pantry', spacePhoto='', detected=[];
const save=()=>{localStorage.setItem(KEY,JSON.stringify(items));render();};
const esc=s=>String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
function show(id){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');$$('.tab').forEach(t=>t.classList.toggle('active',t.dataset.view===id));scrollTo(0,0)}
$$('.tab').forEach(t=>t.onclick=()=>show(t.dataset.view));
$('#scanSpaceHeroBtn').onclick=()=>show('scanView'); $('#viewAllBtn').onclick=()=>show('homeView');
function status(i){if(Number(i.qty)<=0||i.stock==='out')return 'Out';if(i.stock==='low')return 'Low';if(i.stock==='plenty')return 'Plenty';return `${i.qty||1} on hand`}
function render(){
 const sorted=[...items].sort((a,b)=>(b.updated||0)-(a.updated||0));
 $('#recentGrid').innerHTML=sorted.slice(0,4).map(i=>`<div class="item-card"><div class="item-thumb">📦</div><div class="item-body"><b>${esc(i.name)}</b><div class="item-meta">${esc(status(i))} · ${esc(i.location)}</div></div></div>`).join('')||'<div class="empty">Nothing remembered yet.</div>';
 $('#inventoryList').innerHTML=sorted.map(i=>`<div class="inventory-row"><div class="inventory-thumb">📦</div><div class="grow"><b>${esc(i.name)}</b> <span class="stock-pill ${i.stock||''}">${status(i)}</span><div class="inventory-sub">${esc(i.location)}</div><div class="stock-actions"><button data-id="${i.id}" data-stock="out">Out</button><button data-id="${i.id}" data-stock="low">Low</button><button data-id="${i.id}" data-stock="plenty">Plenty</button><button data-id="${i.id}" data-delta="-1">−</button><span>${Number(i.qty)||0}</span><button data-id="${i.id}" data-delta="1">+</button></div></div></div>`).join('')||'<div class="empty">Your house memory is empty.</div>';
 $$('[data-stock]').forEach(b=>b.onclick=()=>{let i=items.find(x=>x.id==b.dataset.id);i.stock=b.dataset.stock;if(i.stock==='out')i.qty=0;else if(i.qty<=0)i.qty=1;i.updated=Date.now();save()});
 $$('[data-delta]').forEach(b=>b.onclick=()=>{let i=items.find(x=>x.id==b.dataset.id);i.qty=Math.max(0,(Number(i.qty)||0)+Number(b.dataset.delta));i.stock=i.qty===0?'out':(i.qty<=1?'low':'plenty');i.updated=Date.now();save()});
}
function check(){let q=$('#searchInput').value.trim().toLowerCase();if(!q)return;let words=q.replace(/ies$/,'y').replace(/s$/,'');let hits=items.filter(i=>{let n=i.name.toLowerCase();return n.includes(q)||n.replace(/ies$/,'y').replace(/s$/,'').includes(words)||words.includes(n.replace(/ies$/,'y').replace(/s$/,''))});let r=$('#resultCard');r.classList.remove('hidden');if(!hits.length)r.innerHTML=`<div class="result-no">✓</div><h3>Nothing similar found</h3><p>We don't currently remember any ${esc(q)}.</p>`;else{let inStock=hits.filter(i=>Number(i.qty)>0&&i.stock!=='out');if(!inStock.length)r.innerHTML=`<div class="result-out">0</div><h3>You're out</h3><p>${esc(hits[0].name)} is remembered, but inventory is at zero.</p>`;else r.innerHTML=`<div class="result-yes">✓</div><h3>You already have this</h3>${inStock.map(i=>`<p><b>${esc(i.name)}</b> · ${status(i)}<br>${esc(i.location)}</p>`).join('')}`}}
$('#searchBtn').onclick=check;$('#searchInput').onkeydown=e=>{if(e.key==='Enter')check()};
$('#itemForm').onsubmit=e=>{e.preventDefault();items.unshift({id:Date.now(),name:$('#itemName').value.trim(),qty:Math.max(0,Number($('#itemQty').value)||0),category:$('#itemCategory').value.trim(),location:$('#itemLocation').value.trim(),notes:$('#itemNotes').value.trim(),stock:Number($('#itemQty').value)<=0?'out':(Number($('#itemQty').value)<=1?'low':'plenty'),updated:Date.now()});e.target.reset();$('#itemQty').value=1;save();show('homeView')};
$$('.space-type').forEach(b=>b.onclick=()=>{$$('.space-type').forEach(x=>x.classList.remove('active'));b.classList.add('active');selectedSpace=b.dataset.space});
function compress(file,max=1280,q=.72){return new Promise((resolve,reject)=>{let fr=new FileReader();fr.onerror=reject;fr.onload=()=>{let im=new Image();im.onload=()=>{let scale=Math.min(1,max/Math.max(im.width,im.height)),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',q))};im.onerror=reject;im.src=fr.result};fr.readAsDataURL(file)})}
$('#spacePhoto').onchange=async e=>{let f=e.target.files[0];if(!f)return;spacePhoto=await compress(f);$('#spacePhotoPreview').innerHTML=`<img src="${spacePhoto}" alt="Selected ${selectedSpace}"><small>Tap to retake</small>`;$('#analyzeSpaceBtn').disabled=false;$('#scanResults').classList.add('hidden')};
$('#analyzeSpaceBtn').onclick=async()=>{if(!spacePhoto)return;$('#scanProgress').classList.remove('hidden');$('#analyzeSpaceBtn').disabled=true;try{let res=await fetch('/api/analyze-space',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({space:selectedSpace,image:spacePhoto})});let data=await res.json();if(!res.ok)throw Error(data.error||'Scan failed');detected=(data.items||[]).map((x,k)=>({id:k,name:x.name,category:x.category,qty:x.quantity_estimate,stock:x.stock_state,confidence:x.confidence,evidence:x.evidence,selected:x.confidence==='high'}));renderDetected();$('#scanResults').classList.remove('hidden')}catch(err){alert(err.message)}finally{$('#scanProgress').classList.add('hidden');$('#analyzeSpaceBtn').disabled=false}};
function renderDetected(){let d=$('#detectedList');d.innerHTML=detected.length?detected.map((x,k)=>`<div class="detected-row"><input type="checkbox" data-check="${k}" ${x.selected?'checked':''}><div class="detected-icon">${x.confidence==='high'?'✓':'?'}</div><div><input class="detected-name" data-name="${k}" value="${esc(x.name)}"><div class="confidence ${x.confidence}">${x.confidence} confidence</div><small>${esc(x.evidence)}</small></div><div class="qty-stepper"><button data-minus="${k}">−</button><span>${x.qty}</span><button data-plus="${k}">+</button></div></div>`).join(''):'<div class="empty">Nothing clearly identifiable. Try a closer, brighter photo.</div>';$$('[data-check]').forEach(c=>c.onchange=()=>{detected[c.dataset.check].selected=c.checked;count()});$$('[data-name]').forEach(n=>n.oninput=()=>detected[n.dataset.name].name=n.value);$$('[data-minus]').forEach(b=>b.onclick=()=>{let x=detected[b.dataset.minus];x.qty=Math.max(0,x.qty-1);renderDetected()});$$('[data-plus]').forEach(b=>b.onclick=()=>{detected[b.dataset.plus].qty++;renderDetected()});count()}
function count(){let n=detected.filter(x=>x.selected).length;$('#selectedCount').textContent=`${n} item${n===1?'':'s'} selected`}
$('#selectAllScan').onclick=()=>{detected.forEach(x=>x.selected=true);renderDetected()};
$('#saveScanBtn').onclick=()=>{let chosen=detected.filter(x=>x.selected);for(let x of chosen){let existing=items.find(i=>i.name.toLowerCase()===x.name.toLowerCase()&&i.location===selectedSpace);if(existing){existing.qty=x.qty;existing.stock=x.qty===0?'out':x.stock;existing.updated=Date.now()}else items.unshift({id:Date.now()+Math.random(),name:x.name,qty:x.qty,stock:x.qty===0?'out':x.stock,category:x.category,location:selectedSpace,source:'space-scan',updated:Date.now()})}save();show('homeView')};
$('#clearBtn').onclick=()=>{if(confirm('Clear all remembered items?')){items=[];save()}};
$('#seedBtn').onclick=()=>{items=[{id:1,name:'HDMI cables',qty:2,stock:'plenty',location:'Garage cabinet',category:'Electronics',updated:Date.now()},{id:2,name:'Pool shock',qty:4,stock:'plenty',location:'Pool storage',category:'Pool',updated:Date.now()-86400000}];save()};
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});render();
